name: Test Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Unit Tests
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Running deployment..."


